# Generated by Django 4.0.4 on 2022-05-17 16:54

import datetime
from django.db import migrations, models
import django.db.models.deletion
import task.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TheResponsible',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=120)),
                ('last_name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254, validators=[task.models.validate_email])),
            ],
        ),
        migrations.CreateModel(
            name='TheTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taskName', models.CharField(max_length=120)),
                ('taskDesc', models.TextField(blank=True)),
                ('start_date', models.DateField(default=datetime.datetime.now)),
                ('end_date', models.DateField(default=datetime.datetime(2022, 5, 18, 12, 54, 13, 691197))),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.theresponsible')),
            ],
        ),
    ]
